-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "zhTW")
if not L then return end

L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = "Alt+右擊添加隨記"
L["(No Title)"] = "（無標題）"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00提示：|cffeda55fCtrl+Shift+左鍵拖拽|cFF00FF00可以移動一個隨記"
L["Add Handy Note"] = "添加隨記"
L["Add this location to TomTom waypoints"] = "在 TomTom 中添加此位置"
L["Configuration for each individual plugin database."] = "為每個外掛程式資料庫單獨配置"
L["Delete Handy Note"] = "刪除隨記"
L["Description/Notes:"] = "描述/注釋："
L["Edit Handy Note"] = "編輯隨記"
L["Enable HandyNotes"] = "啟用 HandyNotes"
L["Enable or disable HandyNotes"] = "啟用或者禁用 HandyNotes"
L["ERROR_CREATE_NOTE1"] = "HandyNotes 不能創建注釋，因為它無法獲得您當前所在的位置。這通常是因為您所在的區域沒有地圖。"
L["HandyNotes"] = "|cff0080ff[地圖]|r寶藏稀有"
L["Icon Alpha"] = "圖示透明度"
L["Icon Scale"] = "圖示縮放"
L["Minimap Icon Alpha"] = "小地圖圖示透明度"
L["Minimap Icon Scale"] = "小地圖圖示縮放"
L["Overall settings"] = "全域設置"
L["Overall settings that affect every database"] = "作用於所有資料庫的全域設置"
L["Plugin databases"] = "外掛程式資料庫"
L["Plugins"] = "外掛程式"
L["Portal"] = "傳送門"
L["Show on continent map"] = "在大陸地圖上顯示"
L["Show the following plugins on the map"] = "在地圖上顯示下列外掛程式"
L["Syntax:"] = "參數："
L["The alpha transparency of the icons"] = "圖示的透明度"
L["The overall alpha transparency of the icons on the Minimap"] = "小地圖上圖示的全域透明度值"
L["The overall alpha transparency of the icons on the World Map"] = "世界地圖上圖示的全域透明度值"
L["The overall scale of the icons on the Minimap"] = "小地圖上圖示的全域縮放值"
L["The overall scale of the icons on the World Map"] = "世界地圖上圖示的全域縮放值"
L["The scale of the icons"] = "圖示的縮放值"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "這些設置可以全域控制 HandyNotes 的外觀及風格。這裡的圖示的縮放和透明度會乘以外掛程式的縮放及透明度。"
L["These settings control the look and feel of the HandyNotes icons."] = "這些設置控制 HandyNotes 圖示的外觀及風格。"
L["Title"] = "標題"
L["World Map Icon Alpha"] = "世界地圖圖示透明度"
L["World Map Icon Scale"] = "世界地圖圖示縮放"

-------------------------------------------------------BFA-Achievments
-- Settings
L["Icon settings"] = "圖示設置"
L["These settings control the look and feel of the icon."] = "這些設置控制圖示的外觀。"
L["Icon scale"] = "圖示縮放"
L["The scale of the icons."] = "圖示的縮放值"
L["Icon alpha"] = "圖示透明度"
L["The alpha transparency of the icons."] = "圖示的透明度"
L["World Map"] = "世界地圖"
L["Show icons on world map"] = "在世界地圖上顯示圖標"
L["Minimap"] = "小地圖"
L["Show icons on the minimap"] = "在小地圖上顯示圖標"
L["What to display"] = "顯示細節"
L["Show found"] = "顯示已發現"
L["Show waypoints for items you've already found?"] = "顯示你已發現的項的節點"
L["Reset hidden nodes"] = "重置隱藏的節點"
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = "重新顯示你用右鍵手動隱藏過的節點。"
L["Create waypoint"] = "創建節點"
L["Hide node"] = "隱藏節點"
L["Close"] = "關閉"

-- 沙丘騎手
L["Along the pyramid edge"] = "沿著金字塔邊緣"
L["On top of the slither snake"] = "在滑動的蛇上方"
L["Entrance"] = "入口"

-- 石刻
L["Inside a building ruins near the mountain"] = "在山附近的廢墟房子裡"
L["Next to broken pillar as you enter the ruins"] = "在廢墟裡面的爛柱子旁邊"
L["Island between Nazmir and Zuldazar zones"] = "納茲米爾和祖達薩之間的島嶼"
L["Near Kel'vax Deathwalker rare"] = "稀有怪死亡行者卡爾瓦科斯附近"

-- 傳說
L["Behind the NPC in the Corner"] = "在角落裡的NPC背後"
L["Above, to the right of the small staircase"] = "在上面，小樓梯的右邊"
L["Next to the river"] = "在河邊"
L["On the wall, behind the torch"] = "在火炬後面的牆上"
L["Above, at the pond on the big stone"] = "在上面，大石頭上的水池"
L["At the destroyed pillar"] = "在爛柱子上"
L["In the eye of the skeleton, outside"] = "在外面的骷髏眼睛裡"
L["Between the roots"] = "樹根的縫隙"
L["At the destroyed pillar on the left"] = "在左邊的爛柱子上"
L["Scroll on the altar"] = "卷軸在祭壇上"
L["At the destroyed wall"] = "在爛牆上"
L["Under water, at the bottom, at the destroyed pillar"] = "在水底的爛柱子上"
L["Scroll next to the altar, behind the mobs"] = "卷軸在小怪後面的祭壇上"
L["In the pond"] = "在水池裡"
L["Next to the withered tree"] = "在枯樹旁邊"

--實事求是，女士
L["Under water"] = "在水下"
L["Behind the scrub"] = "在灌木叢後面"
L["Under water at the foot of the small waterfall"] = "在小瀑布下方的水裡"
L["At the bottom of the upper waterfall"] = "在瀑布的底部"
L["Under the leaning tree"] = "在傾斜的樹下"
L["On the mountain, a bit difficult to find the way up (see path)"] = "在山上，有點難找（仔細看引導）"
L["Path to The Flayed Man: Start"] = "剝皮者引導：開始"
L["Path to The Flayed Man: Step 1"] = "剝皮者引導：第一步"
L["Path to The Flayed Man: Step 2"] = "剝皮者引導：第二步"
L["Path to The Flayed Man: Step 3"] = "剝皮者引導：第三步"
L["Path to The Flayed Man: Step 4"] = "剝皮者引導：第四步"
L["Path to The Flayed Man: End, jump down carefully"] = "剝皮者引導：最後，小心點跳下去"
L["In a cave, at the very back of the wall"] = "在山洞裡，在牆的背面"
L["Path to Protectors of the Forest: cave entrance"] = "森林守護者引導：山洞入口"
L["Lost Spawn of Krag'wa #1"] = "迷路的卡格瓦子嗣 #1"
L["In an underwater cave"] = "在水下的洞穴里"
L["Cave entrance for #1"] = "洞穴入口 #1"
L["Lost Spawn of Krag'wa #2"] = "迷路的卡格瓦子嗣 #2"
L["Cave entrance for #2"] = "洞穴入口 #2"
L["Lost Spawn of Krag'wa #3"] = "迷路的卡格瓦子嗣 #3"
L["Between the huge roots"] = "巨大的根的縫隙中"
L["Lost Spawn of Krag'wa #4"] = "迷路的卡格瓦子嗣 #4"
L["In cave"] = "在洞穴里"
L["Cave entrance for #4"] = "洞穴入口 #4"
L["Lost Spawn of Krag'wa #5"] = "迷路的卡格瓦子嗣 #5"
L["Cave entrance for #5"] = "洞穴入口 #5"
L["Way up to the cave #5"] = "通往洞穴的路 #5"
L["Lost Spawn of Krag'wa #6"] = "迷路的卡格瓦子嗣 #6"
L["Sits up between trees"] = "在樹林中"
L["Lost Spawn of Krag'wa #7"] = "迷路的卡格瓦子嗣 #7"
L["Sits near the bridge behind the big tree"] = "在大樹后面的橋附近"
L["Lost Spawn of Krag'wa #8"] = "迷路的卡格瓦子嗣 #8"
L["Cave entrance for #8"] = "洞穴入口 #8"
L["Lost Spawn of Krag'wa #9"] = "迷路的卡格瓦子嗣 #9"
L["Sits behind a curtain of scrub"] = "在一塊磨砂的簾子后面"
L["Lost Spawn of Krag'wa #10"] = "迷路的卡格瓦子嗣 #10"
L["Sits in a ruin"] = "在廢墟中"
L["ADD to NPCScan"] = "添加到NPCScan"
L["Information for NPCScan and not available."] = "NPCScan的信息不可用"
L["Use item icons"] = "使用物品圖標"
L["Show the icons for items, if known; otherwise, the achievement icon will be used"] = "如果已知則顯示物品圖標，否則顯示成就圖標"
L["Use item tooltips"] = "使用物品提示"
L["Show the full tooltips for items"] = "顯示完整的物品使用提示"
L["Show NPCs"] = "顯示NPCs"
L["Show rare NPCs to be killed, generally for items or achievements"] = "顯示稀有怪擊殺信息，通常為道具或成就"
L["Show treasure"] = "顯示寶箱"
L["Show treasure that can be looted"] = "顯示可獲得的寶箱"
L["Junk"] = "垃圾"
L["Show items which don't count for any achievement"] = "顯示不統計任何成就的物品"
L["Debug"] = "調試"
L["Show quest ids"] = "顯示任務ID"
L["Show the internal id of the quest associated with this node. Handy if you want to report a problem with it."] = "顯示與此節點相關的任務內部ID。用于報告問題。"
L["Show NPCs ids"] = "顯示NPC ID"
L["Show the internal id of the NPC associated with this node. Handy if you want to report a problem with it."] = "顯示與此節點相關的NPC內部ID。用于報告問題。"
L["What to display achievement"] = "如何展示成就"
L["Show Achievement"] = "顯示成就 "
L["Show Achievement that can be looted"] = "顯示可獲得的成就"
L["Use item icons achievement"] = "使用成就獎勵物品圖標"
L["Show Achievements completed"] = "顯示已經獲得的成就"
L["Select achievement"] = "選擇成就"
L["Show the icons Achievement"] = "宣誓成就圖標"
L["Entrance "] = "入口 "
L["Start "] = "開始 "
L["Require item : "] = "必要道具："
L["You can buy them from : "] = "可在此處購買："
L['Treasure Chest'] = '藏寶箱'
L['Small Treasure Chest'] = '小寶箱'
L["On second floor"] = "在二樓"
L["Bottom floor of ship"] = "船的底層"
L["Top of ship"] = "船的高處"
L["Event: kill Da White Shark first"] = "事件：需要先殺死大白鯊"
L["In cave behind waterfall"] = "在瀑布后面的山洞里"
L["Road behind waterfall"] = "瀑布后面的路"
L["In dead hippo's mouth"] = "在河馬尸體的嘴里"
L["Climb the tree"] = "爬到樹上"
L["Use mine cart"] = "使用礦車"
L["Climb the rock arch"] = "爬上石拱門"
L["Climb fallen tree"] = "爬到倒下的樹上"
L["Under sand pile"] = "在沙堆下"
L["Door on East side"] = "在東邊的門上"
L["Path from South side"] = "從南邊的路徑"
L["Enter at top of temple"] = "進入神廟的頂部"
L["Ride the Guardian"] = "騎乘守衛者"
L["In Boralus, on Stomsong Monastary"] = "在伯拉勒斯里，斯托頌修道院"
L["Teleport here from Stormsong, pick up the gem"] = "從斯托頌傳送到這里，拿起寶石"
L["Kill pirates in Freehold until the map drops"] = "擊殺海盜掉落"
L["Entrance to the underwater cave"] = "水下洞穴的入口"
L["Read Damp Scrolls; in the underwater cave, from the monastary"] = "閱讀潮濕的卷軸；從修道院過去的水下洞穴"
L["Read Damp Scrolls; underground"] = "閱讀潮濕的卷軸；地下室"
L["Read Damp Scrolls; upstairs"] = "閱讀潮濕的卷軸；樓上"
L["Read Damp Scrolls"] = "閱讀潮濕的卷軸"
L["Ominous Altar; use it, get teleported, pick up the gem"] = "不祥的祭壇；使用它進行傳送，拿起寶石"
L["Left Down Up Right"] = "左下上右"
L["Right Up Left Down"] = "右上左下"
L["Click on Witch Torch"] = "點擊巫術火把"
L["Get keys from Gorging Raven"] = "從貪吃的烏鴉那里獲得鑰匙"
L["Left Right Down Up"] = "左右下上"
L["On roof"] = "在屋頂上"
L["Top shelf inside shed"] = "棚子里上方的架子上"
L["Climb ladder onto ship"] = "爬梯子上船"
L["Under ship"] = "在船下方"
L["Under platform"] = "在臺子下"
L["Jump onto platform"] = "跳到臺子上"
L["Behind pillar"] = "在柱子后面"
L["Shares spawn timer with Azuresail the Ancient and Kil'Tawan"] = "與雙帆龍藍帆和魔暴龍王科塔爾共享刷新時間"
L["Shares spawn timer with Thunderfoot and Kil'Tawan"] = "與雷龍雷腳和魔暴龍王科塔爾共享刷新時間"
L["South of Savagelands"] = "薩維格蘭南部"
L["Can be found near the road in the grass"] = "能夠在草地附近找到路"
L["South of the Nesingwary's Trek windrider"] = "在奈辛瓦里飛行點的南側"
L["Fighting Ten'gor at crossroad"] = "在路口與恐角龍戰斗"
L["On the road from Zeb'ahari to Tal'gurub"] = "從澤布阿里到塔爾格拉布的路上"
L["Flying close to the road from Vol'dun to Zuldazar"] = "在沃頓到祖達薩的路附近飛行"
L["Ride to Roan Berthold in Southwind Station, follow the road"] = "在南風站騎乘黑白雜色的馬，沿著路走"
L["Inside skeleton under the sand"] = "埋在沙里的骨架下"
L["Hillside above the cave"] = "山洞上的斜坡"
L["Pick one to fight; Dagger from Longfang, mail gloves from Henry"] = "挑選一個戰斗；龍方的匕首，亨利的裝甲拳套"
L["On the beach, between trees"] = "在海灘上，在樹之間"
L["South of Heart of Darkness. Entrance is from the north side of Xal'vor ruins"] = "在黑暗之心的南邊。入口在廢墟的北邊。"
L["In cave, entrance at 73.2 49.7"] = "在山洞里，入口在73.2 49.7"
L["Shrouded Shore, on the hill"] = "被遮擋的海岸，在山上"
L["Lost Spawn of Krag'wa 1"] = "迷路的卡格瓦子嗣 1"
L["Lost Spawn of Krag'wa 2"] = "迷路的卡格瓦子嗣 2"
L["Lost Spawn of Krag'wa 3"] = "迷路的卡格瓦子嗣 3"
L["Lost Spawn of Krag'wa 4"] = "迷路的卡格瓦子嗣 4"
L["Lost Spawn of Krag'wa 5"] = "迷路的卡格瓦子嗣 5"
L["Lost Spawn of Krag'wa 6"] = "迷路的卡格瓦子嗣 6"
L["Lost Spawn of Krag'wa 7"] = "迷路的卡格瓦子嗣 7"
L["Lost Spawn of Krag'wa 8"] = "迷路的卡格瓦子嗣 8"
L["Lost Spawn of Krag'wa 9"] = "迷路的卡格瓦子嗣 9"
L["Lost Spawn of Krag'wa 10"] = "迷路的卡格瓦子嗣 10"
L["Buy %s from %s "] = "從 %s 購買 %s "
L["to Brennadam"] = "前往布倫納丹"
L["Use Cooking for %s"] = "對 %s 使用烹飪"
L["The recipe %s and loot on %s to Waycrest Manor"] = "在維克雷斯莊園獲得 %s 配方"
L["Near the waterfall"] = "瀑布附近"
L["On top of the hill"] = "在山頂上"
L["Near the lake"] = "在湖附近"
L["On top of the island"] = "在島上"
L["Up the mountain right of Warfang Hold"] = "在戰牙要塞右邊的山上"
L["Up the mountain left of Warfang Hold"] = "在戰牙要塞左邊的山上"
L["Near the Shrine of the Storm entrance"] = "風暴神殿入口附近的神龕"
L["On the fireplace mantel"] = "在壁爐臺上"
L["Behind the Jay the Tavern Bard"] = "在酒館吟游詩人杰伊背后"
L["Near the cliff under the trees west of Arom's Stand flight master."] = "在阿羅姆之臺飛行點西邊的懸崖樹下"
L["Between the rocks mid level of the waterfall"] = "在瀑布中段的石縫中"
L["On the mountain north of Fallhaven in the pile of bones."] = "在蕭灣鎮北邊山上的骨堆里"
L["In the tree trunk from the south side"] = "在南邊的樹干里"
L["(Mount known)"] = "(|cFF00FF00已獲得坐騎|r)"
L["(Mount missing)"] = "(|cFFFF0000未獲得坐騎|r)"
L["Pet"] = "寵物"
L["(Toy known)"] = "(|cFF00FF00已獲得玩具|r)"
L["(Toy missing)"] = " (|cFFFF0000未獲得玩具|r)"
L["Retrieving data ..."] = "正在檢索數據…"
L["(itemLinkGreen)"] = "(|cFF00FF00%s|r)"
L["(itemLinkRed)"] = "(|cFFFF0000%s|r)"
L["context_menu_title"] = "阿拉希高地寶藏稀有"
L["context_menu_add_tomtom"] = "添加到TomTom"
L["context_menu_hide_node"] = "隱藏該節點"
L["context_menu_restore_hidden_nodes"] = "恢復所有隱藏節點"
L["Arathi"] = true
L["options_icon_settings"] = "圖標設置"
L["options_icon_settings_desc"] = "圖標設置"
L["options_icons_treasures"] = "寶箱圖標"
L["options_icons_treasures_desc"] = "寶箱圖標"
L["options_scale"] = "大小"
L["options_scale_desc"] = "1-100%"
L["options_opacity"] = "透明度"
L["options_opacity_desc"] = "0透明-1不透明"
L["options_icons_rares"] = "稀有怪圖標"
L["options_icons_rares_desc"] = "稀有怪圖標"
L["options_icons_pet_battles"] = "寵物對戰圖標"
L["options_icons_pet_battles_desc"] = "寵物對戰圖標"
L["options_visibility_settings"] = "可見項設置"
L["options_visibility_settings_desc"] = "可見項設置"
L["options_toggle_treasures"] = "寶箱"
L["options_toggle_rares"] = "稀有怪"
L["options_toggle_battle_pets"] = "寵物戰斗"
L["options_toggle_npcs"] = "NPC"
L["options_toggle_caves"] = "洞穴入口"
L["options_general_settings"] = "常規設置"
L["options_general_settings_desc"] = "常規設置"
L["options_toggle_alreadylooted_rares"] = "顯示已獲得戰利品的稀有怪"
L["options_toggle_alreadylooted_rares_desc"] = "無論是否獲得戰利品，都顯示所有的稀有怪"
L["options_toggle_alreadylooted_treasures"] = "顯示已打開的寶箱"
L["options_toggle_alreadylooted_treasures_desc"] = "無論是否已經打開過，都顯示所有的寶箱"
L["options_toggle_hideKnowLoot"] = "若獲得所有的戰利品，則隱藏稀有怪"
L["options_toggle_hideKnowLoot_desc"] = "無需求了，就別殺別人了"
L["options_tooltip_settings"] = "提示信息"
L["options_tooltip_settings_desc"] = "提示信息"
L["options_toggle_show_loot"] = "顯示戰利品"
L["options_toggle_show_loot_desc"] = "將戰利品的信息添加到提示信息中"
L["options_toggle_show_notes"] = "顯示備注"
L["options_toggle_show_notes_desc"] = "將有價值的備注添加到提示信息中"
L["options_toggle_show_debug"] = "調試"
L["options_toggle_show_debug_desc"] = "顯示調試信息"
L["Alliance only"] = "僅限聯盟"
L["Horde only"] = "僅限部落"

L["Allow left click to open journal to dungeon or raid"] = "允許使用左鍵打開地城或團隊副本的冒險指南"
L["Allow right click to create waypoints with TomTom"] = "允許使用右鍵建立 TomTom 導引箭頭"
L["Continent Alpha"] = "大陸地圖圖示透明度"
L["Continent Scale"] = "大陸地圖圖示縮放大小"
L["Don't show discovered dungeons"] = "不要顯示已發現的地城"
L["Enable TomTom integration"] = "啟用 TomTom 整合"
L["Filter Options"] = "過濾選項"
L["Hide all BfA nodes from the map"] = "隱藏地圖上所有決戰艾澤拉斯的副本圖示"
L["Hide all Broken Isle nodes from the map"] = "隱藏地圖上所有破碎群島的副本圖示"
L["Hide all Cataclysm nodes from the map"] = "隱藏地圖上所有浩劫與重生的副本圖示"
L["Hide all Draenor nodes from the map"] = "隱藏地圖上所有德拉諾的副本圖示"
L["Hide all Northrend nodes from the map"] = "隱藏地圖上所有北裂境的副本圖示"
L["Hide all Outland nodes from the map"] = "隱藏地圖上所有外域的副本圖示"
L["Hide all Pandaria nodes from the map"] = "隱藏地圖上所有潘達利亞的副本圖示"
L["Hide all Vanilla nodes from the map"] = "隱藏地圖上所有艾澤拉斯的副本圖示"
L["Hide Battle for Azeroth"] = "隱藏決戰艾澤拉斯"
L["Hide Broken Isles"] = "隱藏破碎群島"
L["Hide Cataclysm"] = "隱藏浩劫與重生"
L["Hide Draenor"] = "隱藏德拉諾"
L["Hide Instances"] = "隱藏副本"
L["Hide Northrend"] = "隱藏北裂境"
L["Hide Outland"] = "隱藏外域"
L["Hide Pandaria"] = "隱藏潘達利亞"
L["Hide Vanilla"] = "隱藏艾澤拉斯"
L["Invert Lockout"] = "反向顯示已擊殺"
L["Journal Integration"] = "啟用冒險指南整合"
L["Lockout Alpha"] = "已擊殺透明度"
L["Lockout Gray Icon"] = "已擊殺灰色圖示"
L["Lockout Options"] = "首領已擊殺選項"
L["Lockout Tooltip"] = "已擊殺滑鼠提示"
L["Show dungeon locations on the map"] = "在地圖上顯示5人地城的位置"
L["Show Dungeons"] = "顯示地城"
L["Show icons on continent map"] = "在大陸地圖上顯示圖示"
L["Show lockout information on tooltips"] = "在滑鼠提示中顯示首領已擊殺的資訊"
L["Show Mixed"] = "都顯示"
L["Show mixed (dungeons + raids) locations on the map"] = "在地圖上顯示地城和團隊副本的位置"
L["Show on Continent"] = "顯示於大陸地圖"
L["Show raid locations on the map"] = "在地圖上顯示團隊副本的位置"
L["Show Raids"] = "顯示團隊"
L["The alpha of dungeons and raids that are locked to any extent"] = "任何難度的地城和團隊副本首領已擊殺的透明度"
L["The alpha of the icons shown on the continent map"] = "大陸地圖上的圖示透明度"
L["The alpha of the icons shown on the zone map"] = "區域地圖上的圖示透明度"
L["The scale of the icons shown on the continent map"] = "大陸地圖上的圖示大小"
L["The scale of the icons shown on the zone map"] = "區域地圖上的圖示大小"
L["These settings control the look and feel of the icon."] = "這些設定控制圖示的外觀及風格。"
L["This will check for legion and bfa dungeons that have already been discovered. THIS IS KNOWN TO CAUSE TAINT, ENABLE AT OWN RISK."] = "將會檢查軍臨天下和決戰艾澤拉斯已發現的地城。警告: 此功能已知會引起程式碼汙染的錯誤，啟用時請自行承擔風險。"
L["Turn mixed icons grey when ANY dungeon or raid listed is locked"] = "列出的任何地城或團隊已擊殺時，將混合的圖示顯示為灰色。"
L["Use a different alpha for dungeons and raids that are locked to any extent"] = "使用不同的透明度來顯示首領已擊殺的地城和團隊副本 (任何難度)"
L["Use gray icon for dungeons and raids that are locked to any extent"] = "使用灰色圖示來顯示首領已擊殺的地城和團隊副本 (任何難度)"
L["Use Lockout Alpha"] = "使用已擊殺透明度"
L["Zone Alpha"] = "區域地圖圖示透明度"
L["Zone Scale"] = "區域地圖圖示縮放大小"

-------------------------------------------------------MoleMachine
L["Aerie Peak"] = "鷹巢山"
L["Argent Tournament Grounds"] = "銀白聯賽場地"
L["Blackrock Foundry Overlook"] = "黑石鑄造廠眺望"
L["Broken Shore"] = "破碎群島"
L["Elemental Plateau"] = "元素高原"
L["Fel Pits"] = "惡魔深坑"
L["Fire Plume Ridge"] = "火羽山"
L["Inside Blackrock Mountain"] = "黑石山裡面"
L["Ironforge"] = "鐵爐堡"
L["Mole Machine"] = "鑽地機"
L["Neltharion's Vault"] = "奈薩里奧巢穴"
L["Nethergarde Keep"] = "守望堡"
L["One Keg"] = "獨罈集"
L["Ruby Dragonshrine"] = "晶紅龍殿"
L["Shadowforge City"] = "暗爐城"
L["Stormstout Brewery"] = "風暴烈酒酒坊"
L["Stormwind"] = "暴風城"
L["The Great Divide"] = "大裂口"
L["Throne of Flame"] = "烈焰王座"
L["Undiscovered"] = "未發現"

L["Astravar Harbor"] = "艾斯特瓦港"
L["Evermoon Terrace"] = "永月露臺"
L["Falanaar"] = "法拉納爾"
L["Felsoul Hold"] = "魔魂堡"
L["Lunastre Estate"] = "路納斯特莊園"
L["Moon Guard (entrance)"] = "月之守衛 (入口)"
L["Moon Guard Stronghold"] = "月之守衛要塞"
L["Ruins of Elune'eth"] = "伊露恩斯遺址"
L["Sanctum of Order"] = "秩序聖所"
L["Sanctum of Order (entrance)"] = "秩序聖所 (入口)"
L["Tel'anor"] = "泰爾亞諾"
L["Twilight Vineyards"] = "暮光葡萄園"
L["Waning Crescent"] = "弦月旅店"
-------------------------------------------------------------------------------
----------------------------------- MECHAGON ----------------------------------
-------------------------------------------------------------------------------

L["avenger_note"] = "當奧格索普‧奧布諾提斯是訪客時，殺死OOX-Fleetfoot/MG (區域滿地跑)來重生。";
L["beastbot_note"] = "在帕斯卡K1N6型製作一個［野獸機器人動力包］來啟動。";
L["cogstar_note"] = "殺死區域內任何地方的升級版哨衛，直到他傳送進來加強小怪。";
L["crazed_trogg_note"] = "在邦多的機械廠裡使用噴塗機，塗滿油漆的氣囊或機器人，用他大喊的顏色塗上自己。";
L["deepwater_note"] = "在帕斯卡K1N6型製作一個［百噚誘餌］來召喚。";
L["doppel_gang"] = "分身";
L["doppel_note"] = '從每日任務＂輪狂的建造狂熱＂獲得［減壓閥］，與其他兩名玩家一起啟動。';
L["drill_rig"] = "需要鑽探機 ";
L["foul_manifest_note"] = "連接水中的電塔到外圍電塔通電，然後到旁邊山坡上找到開關按下就會出現。";
L["furor_note"] = '在每日任務 "來自諾達希爾的協助" 期間，點擊小藍色蘑菇直到出現。';
L["killsaw_note"] = "在飛逝森林的任何地方出現，似乎殺死鋸刃伐木機器人後比較容易出現。不會在風險投資公司在森林裡的時候出現，那時候沒有伐木機器人。"
L["leachbeast_note"] = "使用［發熱蒸發器線圈］啟動天氣改變裝置，天氣轉為下雨後，擊殺一定數量的濾液怪出現。";
L["nullifier_note"] = '使用藍色卡片－[遠距迴路旁通器] 或是DNT-碰撞轉移裝置駭入啟動。前者為廢料王掉落，後者為鑽探機JD41與JD99的小怪掉落。';
L["scrapclaw_note"] = "離岸在水中。";
L["sparkqueen_note"] = '當每日任務＂有蟲.好多蟲!＂期間，殺死一定數量蜘蛛出現。';
L["rusty_note"] = "在帕斯卡K1N6型上製作一個［個人時光移轉裝置］，以進入不同的未來。只有當克羅米不是訪客時才會出現。";
L["vaultbot_note"] = "風箏到邦多的機械廠的特斯拉線圈，或在帕斯卡K1N6型上製作一個保險庫機器人鑰匙來直接打開。";

L["iron_chest"] = "鐵潮帶鎖箱";
L["mech_chest"] = "機械箱";
L["msup_chest"] = "機械補給箱";
L["rust_chest"] = "老舊生鏽箱子";
L["iron_chest_note"] = "開啟鐵潮帶鎖箱的鑰匙從西湧列島小怪掉落。";
L["msup_chest_note"] = "開啟機械補給箱的鑰匙從西湧列島小怪掉落。";
L["rust_chest_note"] = "開啟老舊生鏽箱子的鑰匙從西湧列島小怪掉落。";

L["rec_rig"] = "廢料回收機"
L["rec_rig_note"] = "要啟動困難模式，使用超級對撞機武器來將所有輻射元素轉換為不穩定輻射元素。寵物可以在兩種難度中獲得。"

L["options_toggle_mech_chest"] = "機械化箱"
L["options_toggle_mech_chest_desc"] = "顯示機械化箱子的位置。有10個獨特的箱子可以每天洗一次，每個箱子有4-5個產卵位置。位置按顏色分組。"
L["options_toggle_locked_chest"] = "鎖定箱子"
L["options_toggle_locked_chest_desc"] = "在西湧列島中顯示上鎖箱子的位置。"
L["options_toggle_recrig"] = "廢料回收機"
L["options_toggle_recrig_desc"] = "顯示廢料回收機的位置以及事件獎賞。"

-------------------------------------------------------------------------------
----------------------------------- NAZJATAR ----------------------------------
-------------------------------------------------------------------------------

L["naz_intro_note"] = "完成入門任務鏈，解鎖Nazjatar上的rares，寶藏和世界任務。"

L["alga_note"] = "注意: 被四個小怪遮掩！";
L["allseer_note"] = "在卡美伊爾低層的任何地方出現。";
L["anemonar_note"] = "在它上方擊殺巨大的擎天魟來啟動。";
L["avarius_note"] = "使用鹵石鎬收集並將彩色晶體放在基座上。 你不必是一個礦工！";
L["banescale_note"] = "有很小的機率在殺死群母後立即出現。";
L["elderunu_note"] = "在卡美伊爾高層的任何地方出現。";
L["gakula_note"] = "驅趕血鳍蝌蚪直到它出現。";
L["glimmershell_note"] = "有小機率出現在微光殼巨蟹的位置。";
L["kelpwillow_note"] = "使用棱彩水晶魅惑［淤泥蛞蝓］後帶給它來啟動。";
L["lasher_note"] = "在土壤中種植發芽的種子並餵養蒼蠅。";
L["matriarch_note"] = "與另外兩位族母共享重生計時器。";
L["needle_note"] = "通常出現在［女王之門］區域。";
L["oronu_note"] = "到沉默市場找到NPC購買［溺水幼鷹獸］寵物帶著它靠近後就可啟動。";
L["rockweed_note"] = "殺死整個區域的失落的Algan和Wayward Algan直到他出現。 建議使用團隊，因為這可能是一個長期的苦工作。";
L["sandcastle_note"] = "使用顯現石在區域內的任何地方顯露寶箱直到它出現。";
L["tidelord_note"] = "殺死三個艾薩利塑能師以及招喚的被釋放的狂潮直到浪潮領主被召喚出來。";
L["tidemistress_note"] = "點擊未受干擾的樣本直到她出現。";
L["urduu_note"] = "在它面前重疊擊殺［鹿角暗礁行者］後來啟動。";
L["voice_deeps_notes"] = "使用脫下來的殼來衝破此岩石。";
L["vorkoth_note"] = "把餌食扔進池中直到它出現。";
L["area_spawn"] = "在周邊地區出現。";
L["cora_spawn"] = "在珊瑚林的任何地方出現。";
L["cave_spawn"] = "在洞穴中出現。";
L["east_spawn"] = "在區域的東半邊任何地方出現。";
L["ucav_spawn"] = "在水下的洞穴出現。";
L["zone_spawn"] = "在整個區域出現。";

L["supply_chest"] = "戰爭補給箱";
L["assassin_looted"] = "當為刺客時可以拾取。"

L["arcane_chest"] = "祕法寶箱";
L["glowing_chest"] = "發光的祕法寶箱";
L["arcane_chest_01"] = "在一些海藻下。";
L["arcane_chest_02"] = "在建築內部的上層";
L["arcane_chest_03"] = "在第二層。";
L["arcane_chest_04"] = "在瀑布上方的水中。";
L["arcane_chest_05"] = "在廢墟中。";
L["arcane_chest_06"] = ""; -- in the open
L["arcane_chest_07"] = "在洞穴的後面。入口位於贊季爾沙灘東邊。";
L["arcane_chest_08"] = "藏在一些海星下面。";
L["arcane_chest_09"] = "在珍珠殼爬行者(暫譯)後面的一個洞穴裡。";
L["arcane_chest_10"] = "在一個脫下來的殼下面。";
L["arcane_chest_11"] = "在山丘的頂部。";
L["arcane_chest_12"] = "在瀑布的頂部。";
L["arcane_chest_13"] = "在懸崖的頂部，在樹後面。";
L["arcane_chest_14"] = "在伊露恩諾神殿內部。";
L["arcane_chest_15"] = "在建築物的右側。";
L["arcane_chest_16"] = "在水下的洞穴，入口在南方。";
L["arcane_chest_17"] = "在瀑布的頂部。";
L["arcane_chest_18"] = "在路徑下方的一個洞穴裡。";
L["arcane_chest_19"] = "在岩石拱門的頂部。 使用滑翔翼（或是飛行）";
L["arcane_chest_20"] = "在山的頂部。";
L["glowing_chest_1"] = "在水下洞穴的後面，防衛鐵塔。";
L["glowing_chest_2"] = "解開線條。";
L["glowing_chest_3"] = "在洞穴的後面。防衛鐵塔。";
L["glowing_chest_4"] = "消掉三個紅色符文。";
L["glowing_chest_5"] = "在洞穴，防衛鐵塔。";
L["glowing_chest_6"] = "解開線條。";
L["glowing_chest_7"] = "消掉四個藍色符文。";
L["glowing_chest_8"] = "在屋頂上。防衛鐵塔。";

L["slimy_cocoon"] = "軟泥的卵";
L["ravenous_slime_note"] = "使用棱彩水晶控制小動物餵養軟泥。重複五天，直到它產生一個帶有寵物的卵。軟泥將一直持續到下一周重置。";
L["slimy_cocoon_note"] = "一隻寵物準備從卵中收集！ 如果在您的階段它沒有出現，那麼卵的冷卻時間就會消失。 更改階段或稍後再回來查看。";

L["cat_figurine"] = "水晶貓雕像"
L["cat_figurine_01"] = "在一個水下洞穴。雕像在露天的地板上。入口在東邊。"
L["cat_figurine_02"] = "在附近瀑布下的一個洞穴裡。 雕像在牆上的海星下面。"
L["cat_figurine_03"] = "在一個水下洞穴。雕像被藏在某些破碎的貝殼下。"
L["cat_figurine_04"] = "在一個水下洞穴。雕像在露天的地板上。"
L["cat_figurine_05"] = "在一個小洞穴。雕像隱藏在地板上的植物後面。"
L["cat_figurine_06"] = "在一個充滿敵對的礁石行者的水下洞穴中。 小雕像在牆上。 入口在北方。"
L["cat_figurine_07"] = "在一個小洞穴。雕像在一些珊瑚的牆上。"
L["cat_figurine_08"] = "在一個小洞穴。躲避祕法圈。 小雕像在後面的高大的岩石上。"
L["cat_figurine_09"] = "在一個水下洞穴。雕像位於天花板的岩石拱門上。"
L["cat_figurine_10"] = "在路徑下方的一個洞穴裡。 雕像在三個桶之間。"


L["mardivas_lab"] = "瑪爾迪瓦斯實驗室";
L["no_reagent"] = "不使用水晶"
L["swater"] = "小深海"
L["gwater"] = "大深海"
L["sfire"] = "小火炎"
L["gfire"] = "大火炎"
L["searth"] = "小土岩"
L["gearth"] = "大土岩"
L["murloco"] = "莫落哥";
L["tentacle_taco"] = "出售 "..ITEM_QUALITY_COLORS[4].hex.."[飢餓使者的觸手捲]|r 如果你是穿著艾薩利怒濤者斗篷。";

L["options_toggle_treasures_nazj"] = "顯示［尋寶追蹤者］成就的箱子位置。"
L["options_toggle_slimes_nazj"] = "飢餓的軟泥"
L["options_toggle_slimes_nazj_desc"] = "顯示已經餵養可以產出戰寵的四種飢餓軟泥的位置。"
L["options_toggle_cats_nazj"] = "貓咪雕像"
L["options_toggle_cats_nazj_desc"] = "顯示'喵出喵咪喵像'成就的水晶貓位置。"
L["options_toggle_misc_nazj"] = "顯示莫洛哥的洞穴以及瑪爾迪瓦斯的實驗室的位置。"

-------------------------------------------------------------------------------
------------------------------------ CAVES ------------------------------------
-------------------------------------------------------------------------------

L["blindlight_cave"] = "盲光洞穴的入口。";
L["caverndark_cave"] = "洞闇恐懼洞穴的入口。";
L["chasmhaunt_cave"] = "裂谷追魂鰻洞穴的入口。";
L["shassera_cave"] = "夏瑟菈洞穴的入口。";

-------------------------------------------------------------------------------
------------------------------------ GEAR -------------------------------------
-------------------------------------------------------------------------------

L["cloth"] = "布甲";
L["leather"] = "皮甲";
L["mail"] = "鎖甲";
L["plate"] = "鎧甲";

L["1h_mace"] = "單手錘";
L["1h_sword"] = "單手劍";
L["1h_axe"] = "單手斧";
L["2h_mace"] = "雙手錘";
L["2h_axe"] = "雙手斧";
L["2h_sword"] = "雙手劍";
L["shield"] = "盾牌";
L["dagger"] = "匕首";
L["staff"] = "法杖";
L["fist"] = "拳套";
L["polearm"] = "長柄";
L["bow"] = "弓";
L["gun"] = "槍";
L["wand"] = "魔杖";
L["crossbow"] = "弩";
L["offhand"] = "副手";
L["warglaives"] = "戰刃";

L["ring"] = "戒指";
L["amulet"] = "項鍊";
L["cloak"] = "披風";
L["trinket"] = "飾品";

-------------------------------------------------------------------------------
---------------------------------- TOOLTIPS -----------------------------------
-------------------------------------------------------------------------------

L["retrieving"] = "檢索物品連結 ...";
L["in_cave"] = "在洞穴。";
L["weekly"] = "每週";
L["normal"] = "普通";
L["hard"] = "困難";
L["mount"] = "坐騎";
L["pet"] = "寵物";
L["toy"] = "玩具";
L["completed"] = "已完成"
L["incomplete"] = "未完成"
L["known"] = "已收藏"
L["missing"] = "缺少"
L["unobtainable"] = "無法獲得"
L["unlearnable"] = "未學習"
---------------------------------- VISIBILITY ---------------------------------

L["options_visibility_settings"] = "可見度";
L["options_general_settings"] = "一般";
L["options_toggle_looted_rares"] = "永遠顯示所有稀有";
L["options_toggle_looted_rares_desc"] = "顯示所有稀有不論拾取狀態";
L["options_toggle_looted_treasures"] = "已經拾取的寶藏";
L["options_toggle_looted_treasures_desc"] = "顯示所有寶藏不論拾取狀態";
L["options_toggle_hide_done_rare"] = "隱藏稀有，如果物品都已收藏";
L["options_toggle_hide_done_rare_desc"] = "隱藏全部拾取物品都已收藏的稀有。";
L["options_toggle_hide_minimap"] = "隱藏小地圖的所有圖示";
L["options_toggle_hide_minimap_desc"] = "在小地圖上隱藏來自此插件的所有圖示，並且只顯示在大地圖上。";

L["options_toggle_battle_pets_desc"] = "顯示戰寵訓練師與NPC的位置。";
L["options_toggle_battle_pets"] = "戰寵";
L["options_toggle_caves_desc"] = "顯示其他節點的洞穴入口。";
L["options_toggle_caves"] = "洞穴";
L["options_toggle_misc"] = "雜項";
L["options_toggle_npcs"] = "NPC";
L["options_toggle_rares_desc"] = "顯示稀有NPC的位置。";
L["options_toggle_rares"] = "稀有";
L["options_toggle_supplies_desc"] = "顯示所有戰爭補給箱可能的位置。";
L["options_toggle_supplies"] = "戰爭補給掉落";
L["options_toggle_treasures"] = "寶藏";

