local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("GoldRunCWOD") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Jade Plate Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Saltstone Plate Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Tyrant Plate Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Bloodscale Plate Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Ebonhold Mail Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Ironhide Mail Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Bloodlust Mail Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Ancient Mail Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Imposing Leather Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Imperial Leather Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Bonechewer Leather Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Arachnidian Cloth Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Hibernal Cloth Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Master's Cloth Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Daily Runs\\Resilient Cloth Set Transmog")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Green Cabbage")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mogu Pumpkin")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Juicycrunch Carrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Scallion")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Red Blossom Leek")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Witchberries")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Jade Squash")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Striped Melon")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Pink Turnips")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\White Turnips")
