local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
ZygorGuidesViewer.Gold.guides_loaded=true
if ZGV:DoMutex("GoldGatherH") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Strange Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Illusion Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Arcane Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Infinite Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Hypnotic Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Spirit Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Draenic Dust")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Deviate Fish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Oily Blackmouth/Firefin Snapper/Stonescale Eel")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Glassfin Minnow/Pygmy Suckerfish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Albino Cavefish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Emperor Salmon/Krasarang Paddlefish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Giant Mantis Shrimp/Reef Octopus")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Golden Carp")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Jade Lungfish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Jewel Danio")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Redbelly Mandarin/Emperor Salmon")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Spinefish")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Tiger Gourami/Golden Carp")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Abyssal Gulper Eel Flesh/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Abyssal Gulper Eel Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blackwater Whiptail Flesh/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blackwater Whiptail Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blind Lake Sturgeon Flesh/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blind Lake Sturgeon Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fat Sleeper Flesh/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fat Sleeper Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fire Ammonite Tentacle/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Jawless Skulker Flesh/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Sea Scorpion Segment/Crescent Saberfish Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Sea Scorpion Segment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blindweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Bruiseweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Dragon's Teeth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Dreamfoil/Black Lotus (15-30)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Dreamfoil/Black Lotus (15-30)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fadeleaf")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Firebloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ghost Mushroom (Un'Goro Crater)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ghost Mushroom (Zangarmarsh - Outland)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Golden Sansam")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Grave Moss")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Gromsblood")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Icecap")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Khadgar's Whisker")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Kingsblood")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Liferoot")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Mageroyal")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Mountain Silversage")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Purple Lotus/Wildvine")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Sorrowmoss")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Stranglekelp")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Stranglekelp (Speedbarge Diving Helm)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Sungrass")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Swiftthistle/Briarthorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Wildvine (Kill Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ancient Lichen")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Dreaming Glory")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Felweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Mana Thistle")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Netherbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nightmare Vine")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ragveil")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Terocone")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Adder's Tongue")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fire Leaf")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Goldclover/Deadnettle")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Icethorn/Lichbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Talandra's Rose")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Tiger Lily/Deadnettle")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Azshara's Veil")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Heartblossom/Cinderbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Stormvine")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Twilight Jasmine")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Whiptail")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fool's Cap")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Green Tea Leaf")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Silkweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Snow Lily")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Frostweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Starflower")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fireweed")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Gorgrond Flytrap")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nagrand Arrowbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Talador Orchid")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Dusky Pigment/Verdant Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Golden Pigment/Burnt Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Emerald Pigment/Indigo Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Violet Pigment/Ruby Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Silvery Pigment/Sapphire Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nether Pigment/Ebon Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Azure Pigment/Icy Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ashen Pigment/Burning Embers")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Misty Pigment/Shadow Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Cerulean Pigment")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Tigerseye, Malachite")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Shadowgem, Moss Agate, Lesser Moonstone, Jade")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Citrine, Aquamarine")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Huge Emerald, Large Opal, Azerothian Diamond, Blue Sapphire, Star Ruby")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Golden Draenite, Azure Moonstone, Blood Garnet, Deep Peridot, Flame Spessarite, Shadow Draenite")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Adamantite Powder, Living Ruby, Talasite, Nightseye, Star Of Elune, Dawnstone, Noble Topaz")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Huge Citrine, Shadow Crystal, Chalcedony, Bloodstone, Sun Crystal, Dark Jade")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Hessonite, Alicite, Carnelian, Nightstone, Jasper, Zephyrite")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Alexandrite, Sparkling Shard, Pandarian Garnet, Roguestone, Sunstone, Lapis Lazuli, Tiger Opal, Imperial Amethyst, Primordial Ruby, River's Heart, Wild Jade, Sun's Raidance, Vermilion Onyx")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Gold Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Iron Ore/Heavy Stone")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Mithril Ore/Solid Stone")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Thorium Ore/Dense Stone/Truesilver Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Tin Ore/Silver Ore/Coarse Stone")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Adamantite Ore/Eternium Ore/Khorium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fel Iron Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Cobalt Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Saronite Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Titanium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Elementium Ore/Pyrite Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Obsidium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Black Trillium Ore/White Trillium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Ghost Iron Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Kyparite")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blackrock/True Iron Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Deviate Scale/Perfect Deviate Scale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Heavy Leather/Heavy Hide")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Thick Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Rugged Leather/Rugged Hide (Onyxia's Lair)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Rugged Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Turtle Scale/Thick Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Black Whelp Scale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Warbear Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Scorpid Scale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Devilsaur Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Heavy Scorpid Scale/Thick Leather/Rugged Leather/Rugged Hide")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Deepsea Scale/Savage Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Knothide Leather (Karazhan)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Knothide Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Wind Scale/Knothide Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nether Dragonscales")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Thick Clefthoof Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fel Scales/Crystal Infused Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Cobra Scale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Fel Hide")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Borean Leather (Gundrak)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Borean Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Savage Leather/Pristine Hide (Tol Barad)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Icy Dragonscale/Arctic Fur")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Nerubian Chitin")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Jormungar Scale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Savage Leather/Pristine Hide (Twilight Highlands)")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Blackened Dragonscale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Exotic Leather")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Prismatic Scale")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Gathering\\Raw Beast Hide")
