local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
ZygorGuidesViewer.Gold.guides_loaded=true
if ZGV:DoMutex("GoldFarmCWOD") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Linen Cloth/Wool Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Silk Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Runecloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Felcloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Righteous Orb, Mageweave Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mageweave Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Netherweave Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Frostweave Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Iceweb Spider Silk")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Embersilk Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Windwool Cloth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Sumptuous Fur")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Zesty Clam Meat, Black Pearl, Iridescent Pearl, Golden Pearl")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Small Egg")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Stringy Wolf Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Chunk Of Boar Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raptor Egg, Raptor Hide, Raptor Flesh, Large Fang")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Buzzard Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Jaggal Clam Meat, Jaggal Pearl, Shadow Pearl")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Siren's Tear, Northsea Pearl")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Viseclaw Meat, Raw Crab Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Tiger Steak")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mushan Ribs")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Turtle Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Wildfowl Breast")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Crocolisk Belly")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Boar Meat, Rylak Egg")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Talbuk Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Riverbeast Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Raw Clefthoof Meat")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Globe Of Water, Essence Of Water, Elemental Water")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Breath Of Wind, Essence Of Air, Elemental Air")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Core Of Earth, Essence Of Earth, Elemental Earth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Essence Of Fire, Elemental Fire, Heart of Fire")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Essence Of Undeath")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Ichor Of Undeath")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Air")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Earth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Fire")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Mana")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Life")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Shadow")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Mote Of Water")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Frozen Orb")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Eternal Air, Crystallized Air")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Eternal Earth, Crystallized Earth")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Eternal Fire, Crystallized Fire")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Eternal Life, Crystallized Life")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Eternal Shadow, Crystallized Shadow")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Eternal Water, Crystallized Water")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Chaos Orb")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Volatile Fire")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Volatile Water")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Volatile Air")
ZygorGuidesViewer:RegisterGuidePlaceholder("GOLD\\Farming\\Volatile Earth")
