local L = LibStub("AceLocale-3.0"):NewLocale("WorldBossStatus", "zhTW")

if not L then
	return
end

L["Automatically track holiday bosses during world events."] = "當在世界事件期間自動追蹤節日首領。"
L["Available"] = "此首領本週未被擊敗和有掉落可用。"
L["Bonus Roll Options"] = "加成骰選項"
L["Bonus Rolls"] = "加成骰"
L["Bosses"] = "首領"
L["Boss Options"] = "首領選項"
L["Character"] = "角色"
L["Character Options"] = "角色選項"
L["Characters"] = "角色"
L["Click to open the options menu"] = "點擊打開選項菜單"
L["Click to remove the selected tracked character."] = "點擊以移除已選擇的追蹤角色。"
L["Defeated"] = "已擊殺"
L["Enable"] = "啟用"
L["Enable hiding inactive characters."] = "啟用隱藏未活動角色。"
L["Enable level restriction."] = "啟用等級限制。"
L["General Options"] = "一般選項"
L["Hide characters that have been inactive for this many days."] = "隱藏已經好多天沒活動的角色。"
L["Hide Inactive Characters"] = "隱藏未活動角色"
L["Inactivity Threshold (days)"] = "未活動門檻(天數)"
L["Level Restriction"] = "等級限制"
L["Minimap Button"] = "小地圖按鈕"
L["Minimum Level"] = "最低等級"
L["On this account"] = "此帳號"
L["On this realm"] = "此伺服器"
L["Realm"] = "陣營"
L["Remove"] = "移除"
L["Remove Tracked Characters"] = "移除追蹤的角色"
L["Select a realm to remove a tracked character from."] = "選擇一個要移除追蹤角色的陣營。"
L["Select the currencies you would like to track."] = "選擇您想要追蹤的貨幣。"
L["Select the tracked character to remove."] = "選擇此追蹤的角色來移除。"
L["Select the world bosses you would like to track."] = "選擇您想要追蹤的世界首領。"
L["Show Characters"] = "顯示角色"
L["Show characters on this realm."] = "顯示此陣營的角色。"
L["Show characters on this WoW account."] = "顯示此魔獸帳戶的角色。"
L["Show characters this level and higher."] = "顯示高於此等級的角色。"
L["The Celestials"] = "四大天尊"
L["Toggles the display of the minimap button."] = "切換顯示小地圖按鈕。"
L["Toggles the display of this world boss."] = "切換世界首領顯示。"
L["Tracked Bosses"] = "追蹤的首領"
L["Tracked Currencies"] = "追蹤的貨幣"
L["Track holiday bosses"] = "追蹤節日首領"
L["Undefeated"] = "未擊殺"
L["World Bosses"] = "世界首領"
L["World Boss Status"] = "世界首領狀態"
