local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("DailiesCDRAGON") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Azure Span World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Emerald Dream World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Forbidden Reach World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Ohn'ahran Plains World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Thaldraszus World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Waking Shores World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Zaralek Cavern World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Dragonscale Expedition\\Dragonscale Basecamp Weekly Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Grimtusk's Fishing Hole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\River Mouth Fishing Hole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Tyrhold Fishing Hole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Roaring Dragonspring Fishing Hole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Maruuk Centaur\\Aylaag Outpost Daily Quests (Rusza'thar Reach)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Maruuk Centaur\\Aylaag Outpost Daily Quests (Pinewood Post)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Maruuk Centaur\\Aylaag Outpost Daily Quests (Eaglewatch Outpost)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Obsidian Citadel Weekly Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Siege on Dragonbane Keep")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\A Cataloger's Paradise")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\A Climber's Calling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Dragon Isles Emissary")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Forbidden Reach Envoy Dailies")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Dragonskull Island Fishing Hole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Sniffenseeking!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Snail Racing Dailies")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Suffusion Camp (Ohn'ahran Plains)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Suffusion Camp (The Azure Span)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Researchers Under Fire")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Time Rifts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Little Scales Daycare")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Eon's Fringe Dailies")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Little Scales Daycare Dailies")
