local myaddon = ...
local L = LibStub("AceLocale-3.0"):NewLocale(myaddon, "ruRU", false)

if not L then return end

-- Delves
L["Sturdy Chest"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest Note"] = "|cFFFFFFFFОткройте прочный сундук|r"
L["Sturdy Chest 1"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 1 Note"] = "Спрыгните со второго этажа на кран и пройдите вперед."
L["Sturdy Chest 2"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 2 Note"] = "До этого места можно добраться, спрыгнув с каменной платформы возле входа."
L["Sturdy Chest 3"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 3 Note"] = "В эту зону можно попасть, спрыгнув с корабля босса."
L["Sturdy Chest 4"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 4 Note"] = "Он на выступе над комнатой. Есть точка захвата, чтобы туда попасть. Во время сюжета |cFF1EFF00Странные потрясения|r."
L["Sturdy Chest 5"] = "|cFFFFFFFFПрочный сундук 3|r"
L["Sturdy Chest 5 Note"] = "После босса не прыгайте в яму, а проверьте столб внизу к западу от главного пути."
L["Sturdy Chest 6"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 6 Note"] = "Сразу после сундука 3 спрыгните на деревянный выступ внизу на западе."
L["Sturdy Chest 7"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 7 Note"] = "На небольшой платформе под главной тропой."
L["Sturdy Chest 8"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 8 Note"] = "Обойдите сокровищницу и поднимитесь по тропинке. Проверьте один куст там наверху."
L["Sturdy Chest 9"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 9 Note"] = "Под водой - содержит игрушку |cFF0070DDДревний голем|r."
L["Sturdy Chest 10"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 10 Note"] = "Гриб с помощью которого вы допрыгнуть до последнего сундука."
L["Sturdy Chest 11"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 11 Note"] = "Запрыгните на строительные леса."
L["Sturdy Chest 12"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 12 Note"] = "Под водой"
L["Sturdy Chest 13"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 13 Note"] = "Во время сюжета |cFF1EFF00Спасение Прядильщицы|r."
L["Sturdy Chest 14"] = "|cFFFFFFFFПрочный сундук|r"
L["Sturdy Chest 14 Note"] = "Во время сюжета |cFF1EFF00Жертвы пыток|r."

L["Wrapped Spool"] = "|cFFFFFFFFГоловоломка|r"
L["Wrapped Spool Note"] = "|cFFFFFFFFРешите головоломку и получите усиление.|r"
L["Wrapped Spool 1"] = "|cFFFFFFFFУсиление|r"
L["Wrapped Spool 1 Note"] = "|cFFFFFFFFПолучите усиление.|r"

-- Waypoints
L["Create waypoint"] = "Создать путевую точку"
L["Create all waypoints"] = "Создать все путевые точки"
L["Hide node"] = "Скрыть точку"
L["Close"] = "Закрыть"

-- Options
L["Icon settings"] = "Настройки Значков"
L["These settings control the look of the icon."] = "Эти настройки управляют внешним видом значка."
L["Icon Scale"] = "Масштаб Значков"
L["The scale of the icons"] = "Масштаб Значков"
L["Icon Alpha"] = "Альфа Значок"
L["The alpha transparency of the icons"] = "Прозрачность значков"
L["World Map"] = "Карта Мира"
L["Show icons on world map"] = "Показать значки на карте мира"
L["Minimap"] = "Мини-карта"
L["Show icons on the minimap"] = "Показать значки на мини-карте"
L["What to display"] = "Что отображать"
L["Show Zamros"] = "Показать места фарма золота"
L["Show Zamros gold"] = "Показать точки активностей, с помощью которых можно зарабатывать золото"
L["Reset hidden nodes"] = "Сбросить скрытые точки"
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = "Показать все точки, которые вы вручную скрыли, щелкнув по ним правой кнопкой мыши и выбрав \"скрыть\"."